### ISSUE TITLE
[Fix] - 굿즈샵 페이지 체크

### ISSUE THREAD

**Issue by seokachu** [seokachu/IVE#20]
### Todo
- [x] 굿즈샵 페이지 인기순 정렬 적용
- [x] 굿즈샵 페이지 인기순 select 박스 체크 안되는 현상
- [x] 무한스크롤 적용 후 타입 에러
- [x] goTop 유틸 추가
