### ISSUE TITLE
[Fix] - header 체크 리스트

### ISSUE THREAD

**Issue by seokachu** [seokachu/IVE#22]
### Todo
- [x] Header navigation 보고있는 페이지 폰트사이즈 굵게 적용
- [x] 로그아웃 시 찜 되어있는 목록 없애기
- [x] 반응형 체크 확인
